import type { Transaction } from "@/types/transaction";

// TODO: replace with transactions fetched from /api/transactions via react-query.
export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "txn-1",
    title: "Monthly salary",
    amount: 45000,
    type: "income",
    categoryId: "salary",
    walletId: "kbank-savings",
    date: new Date(2026, 8, 1),
  },
  {
    id: "txn-2",
    title: "Weekly groceries",
    amount: 850,
    type: "expense",
    categoryId: "food-drink",
    walletId: "cash",
    date: new Date(2026, 8, 2),
    note: "Weekly groceries at Big C",
  },
  {
    id: "txn-3",
    title: "Grab ride",
    amount: 120,
    type: "expense",
    categoryId: "transport",
    walletId: "credit-card",
    date: new Date(2026, 8, 2),
  },
  {
    id: "txn-4",
    title: "Website design project",
    amount: 8000,
    type: "income",
    categoryId: "freelance",
    walletId: "scb-checking",
    date: new Date(2026, 8, 3),
    note: "Client: Nomad Coffee website",
  },
  {
    id: "txn-5",
    title: "New running shoes",
    amount: 1990,
    type: "expense",
    categoryId: "shopping",
    walletId: "credit-card",
    date: new Date(2026, 8, 4),
  },
  {
    id: "txn-6",
    title: "Mom's birthday gift",
    amount: 500,
    type: "expense",
    categoryId: "gifts",
    walletId: "cash",
    date: new Date(2026, 8, 5),
    note: "Gift for mom's birthday",
  },
  {
    id: "txn-7",
    title: "Dividend payout",
    amount: 2300,
    type: "income",
    categoryId: "investment",
    walletId: "scb-checking",
    date: new Date(2026, 8, 6),
  },
  {
    id: "txn-8",
    title: "Lunch with friends",
    amount: 320,
    type: "expense",
    categoryId: "food-drink",
    walletId: "cash",
    date: new Date(2026, 8, 7),
  },
  {
    id: "txn-9",
    title: "Taxi to airport",
    amount: 450,
    type: "expense",
    categoryId: "transport",
    walletId: "credit-card",
    date: new Date(2026, 8, 8),
  },
  {
    id: "txn-10",
    title: "React course",
    amount: 1200,
    type: "expense",
    categoryId: "shopping",
    walletId: "kbank-savings",
    date: new Date(2026, 8, 8),
    note: "Udemy course - Advanced React",
  },
  {
    id: "txn-11",
    title: "Side gig payment",
    amount: 3500,
    type: "income",
    categoryId: "freelance",
    walletId: "cash",
    date: new Date(2026, 8, 9),
  },
  {
    id: "txn-12",
    title: "Morning coffee",
    amount: 65,
    type: "expense",
    categoryId: "food-drink",
    walletId: "cash",
    date: new Date(2026, 8, 9),
  },
  {
    id: "txn-13",
    title: "Stock sale profit",
    amount: 1500,
    type: "income",
    categoryId: "investment",
    walletId: "scb-checking",
    date: new Date(2026, 7, 28),
    note: "Sold SET50 index shares",
  },
  {
    id: "txn-14",
    title: "Wedding gift",
    amount: 2000,
    type: "expense",
    categoryId: "gifts",
    walletId: "credit-card",
    date: new Date(2026, 7, 25),
  },
];
