import type { Transaction } from "@/types/transaction";

// TODO: replace with transactions fetched from /api/transactions via react-query.
// Seed covers Aug-Oct 2026, matching src/mocks/mockWallets.ts and
// src/mocks/mockCategories.ts so wallet balances, saving-goal progress and
// category totals all agree with each other.
export const MOCK_TRANSACTIONS: Transaction[] = [
  // Decimal tests
  {
    id: "txn-dec-1",
    title: "Tax refund (with decimal)",
    amount: 99.99,
    type: "income",
    walletId: "decimal-test",
    date: new Date(2026, 9, 3),
  },
  {
    id: "txn-dec-2",
    title: "Salary (with decimal)",
    amount: 4500.50,
    type: "income",
    walletId: "decimal-test",
    date: new Date(2026, 9, 3),
  },
  {
    id: "txn-dec-3",
    title: "Coffee (no decimal)",
    amount: 120,
    type: "expense",
    categoryId: "food-drink",
    walletId: "decimal-test",
    date: new Date(2026, 9, 2),
  },
  // October 2026
  {
    id: "txn-1",
    title: "Grab",
    amount: 180,
    type: "expense",
    categoryId: "transport",
    walletId: "daily",
    date: new Date(2026, 9, 2),
    note: "Siam → home",
  },
  {
    id: "txn-2",
    title: "Coffee Beans Co.",
    amount: 145,
    type: "expense",
    categoryId: "food-drink",
    walletId: "daily",
    date: new Date(2026, 9, 2),
  },
  {
    id: "txn-3",
    title: "Freelance tutoring",
    amount: 2500,
    type: "income",
    categoryId: "freelance",
    walletId: "daily",
    date: new Date(2026, 9, 1),
    note: "Math class, 5 hrs",
  },
  {
    id: "txn-4",
    title: "Monthly saving",
    amount: 3000,
    type: "income",
    categoryId: "saving",
    walletId: "emergency-fund",
    date: new Date(2026, 9, 1),
  },
  {
    id: "txn-5",
    title: "7-Eleven",
    amount: 89,
    type: "expense",
    categoryId: "food-drink",
    walletId: "daily",
    date: new Date(2026, 9, 1),
  },
  {
    id: "txn-6",
    title: "Electricity bill",
    amount: 890,
    type: "expense",
    categoryId: "bills",
    walletId: "daily",
    date: new Date(2026, 9, 1),
    note: "September usage",
  },
  // September 2026
  {
    id: "txn-7",
    title: "Central World",
    amount: 1240,
    type: "expense",
    categoryId: "shopping",
    walletId: "daily",
    date: new Date(2026, 8, 30),
  },
  {
    id: "txn-8",
    title: "Shabu dinner",
    amount: 640,
    type: "expense",
    categoryId: "food-drink",
    walletId: "daily",
    date: new Date(2026, 8, 28),
  },
  {
    id: "txn-9",
    title: "BTS top-up",
    amount: 300,
    type: "expense",
    categoryId: "transport",
    walletId: "daily",
    date: new Date(2026, 8, 25),
  },
  {
    id: "txn-10",
    title: "Uniqlo",
    amount: 1620,
    type: "expense",
    categoryId: "shopping",
    walletId: "daily",
    date: new Date(2026, 8, 20),
  },
  {
    id: "txn-11",
    title: "Trip savings",
    amount: 5000,
    type: "income",
    categoryId: "saving",
    walletId: "japan-trip",
    date: new Date(2026, 8, 15),
  },
  {
    id: "txn-12",
    title: "Freelance tutoring",
    amount: 4500,
    type: "income",
    categoryId: "freelance",
    walletId: "daily",
    date: new Date(2026, 8, 15),
  },
  {
    id: "txn-13",
    title: "Grab",
    amount: 210,
    type: "expense",
    categoryId: "transport",
    walletId: "daily",
    date: new Date(2026, 8, 12),
  },
  {
    id: "txn-14",
    title: "Café Amazon",
    amount: 160,
    type: "expense",
    categoryId: "food-drink",
    walletId: "daily",
    date: new Date(2026, 8, 9),
  },
  {
    id: "txn-15",
    title: "Water bill",
    amount: 180,
    type: "expense",
    categoryId: "bills",
    walletId: "daily",
    date: new Date(2026, 8, 5),
  },
  {
    id: "txn-16",
    title: "Groceries",
    amount: 980,
    type: "expense",
    categoryId: "food-drink",
    walletId: "daily",
    date: new Date(2026, 8, 3),
    note: "Big C",
  },
  {
    id: "txn-17",
    title: "Monthly saving",
    amount: 3000,
    type: "income",
    categoryId: "saving",
    walletId: "emergency-fund",
    date: new Date(2026, 8, 1),
  },
  {
    id: "txn-18",
    title: "Salary deposit",
    amount: 32000,
    type: "income",
    categoryId: "salary",
    walletId: "daily",
    date: new Date(2026, 8, 1),
  },
  // August 2026
  {
    id: "txn-19",
    title: "Shopee",
    amount: 2300,
    type: "expense",
    categoryId: "shopping",
    walletId: "daily",
    date: new Date(2026, 7, 28),
  },
  {
    id: "txn-20",
    title: "Team lunch",
    amount: 450,
    type: "expense",
    categoryId: "food-drink",
    walletId: "daily",
    date: new Date(2026, 7, 24),
  },
  {
    id: "txn-21",
    title: "Electricity bill",
    amount: 920,
    type: "expense",
    categoryId: "bills",
    walletId: "daily",
    date: new Date(2026, 7, 19),
  },
  {
    id: "txn-22",
    title: "Trip savings",
    amount: 3500,
    type: "income",
    categoryId: "saving",
    walletId: "japan-trip",
    date: new Date(2026, 7, 15),
  },
  {
    id: "txn-23",
    title: "Grab",
    amount: 260,
    type: "expense",
    categoryId: "transport",
    walletId: "daily",
    date: new Date(2026, 7, 12),
  },
  {
    id: "txn-24",
    title: "Groceries",
    amount: 1120,
    type: "expense",
    categoryId: "food-drink",
    walletId: "daily",
    date: new Date(2026, 7, 6),
  },
  {
    id: "txn-25",
    title: "Monthly saving",
    amount: 3000,
    type: "income",
    categoryId: "saving",
    walletId: "emergency-fund",
    date: new Date(2026, 7, 1),
  },
  {
    id: "txn-26",
    title: "Salary deposit",
    amount: 30000,
    type: "income",
    categoryId: "salary",
    walletId: "daily",
    date: new Date(2026, 7, 1),
  },
];
